var app = angular.module('drsApp.reviewerApplication');
  app.controller('disciplineController', disciplineController)

  function disciplineController($scope){
    $scope.disciplines=[
      "Agriculture",
      "Anthropology",
      "Applied Mathematics",
      "Archaeology",
      "Architecture and design",
      "Area studies",
      "Arts",
      "Biology",
      "Business",
      "Chemistry",
      "Computer sciences",
      "Cultural and ethnic studies",
      "Divinity",
      "Earth sciences",
      "Economics",
      "Education",
      "Engineering and technology",
      "Environmental studies and forestry",
      "Family and consumer science",
      "Formal sciences",
      "Gender and sexuality studies",
      "Geography",
      "Human history",
      "Human physical performance and recreation",
      "Humanities",
      "Intelligence",
      "Journalism, media studies and communication",
      "Law",
      "Library and museum studies",
      "Linguistics",
      "Literature",
      "Logic",
      "Mathematics",
      "Medicine",
      "Military sciences",
      "Natural sciences",
      "Philosophy",
      "Physics",
      "Political science",
      "Psychology",
      "Public administration",
      "Public policy",
      "Pure Mathematics",
      "Religion",
      "Social sciences",
      "Social work",
      "Sociology",
      "Space sciences",
      "Statistics",
      "Systems science",
      "Transportation",
      "Other"
    ];
  };
